# NEJ-RS

# 1. Name
name: Scheduled Workflow  

# 2. Event
on: 
  schedule: # every 5 minutes 
    - cron: "*/5 * * * *" 
        # cron: command run-on

# 3. Job 
jobs:
  scheduled: # 4. Runner
    runs-on: ubuntu-latest

# 5. Steps 
    steps:
      - name: Notify
        run: echo "Scheduled Workflow Executed Successfully"
